server:
  port: 8103

spring:
  application:
    name: config
#  config配置
  cloud:
    config:
      username: 1006556989@qq.com
      password:
      label: master
      server:
        git:
          uri: https://github.com/ratelCloud/cloud-config.git
          searchPaths: /**


#eureka客户端配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://ratel:ratel-123@localhost:2100/eureka/






